version: '3.7'

networks:
    back:
        driver: bridge
    reverse-proxy:
        external: true

services:
    srvc_mariadb:
        container_name: ${PROJECT_NAME}_mariadb
        image: mariadb:${MARIADB_VERSION}
        restart: always
        networks:
            - back
        environment:
            - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MARIADB_DATABASE=${DATABASE_NAME}
            - MARIADB_USER=${DATABASE_USER}
        volumes:
            - database_data:/var/lib/mysql:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/mysql/data:rw
        healthcheck:
          test: ["CMD-SHELL", "exit | mysql -u${DATABASE_USER} -p${DATABASE_PASSWORD}" ]
          interval: 6s
          timeout: 4s
          retries: 5

    srvc_php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: ./docker/php
            args:
                - IMAGE=${PRESTASHOP_IMAGE}
                - DATABASE_DRIVER=${DATABASE_DRIVER}
                - NODE_VERSION=${NODE_VERSION}
        environment:
            - DISABLE_MAKE=1
            - PS_DOMAIN=${PROJECT_NAME}.${BASE_DOMAIN}
            - PS_HANDLE_DYNAMIC_DOMAIN=0
            - DB_SERVER=srvc_mariadb
            - DB_PORT=${DATABASE_PORT}
            - DB_NAME=${DATABASE_NAME}
            - DB_PREFIX=ps_
            - DB_USER=${DATABASE_USER}
            - DB_PASSWD=${DATABASE_PASSWORD}
            - ALLOW_EMPTY_PASSWORD=no
            - PS_INSTALL_AUTO=1
            - PS_ERASE_DB=0
            - PS_INSTALL_DB=0
            - PS_ENABLE_SSL=1
            - PS_FOLDER_ADMIN=admin-dev
            - PS_FOLDER_INSTALL=install
            - PS_DEV_MODE=1
            - PS_LANGUAGE=fr
            - PS_COUNTRY=FR
            - ADMIN_MAIL=admin@docker.local
            - ADMIN_PASSWD=ShopAdmin!
        depends_on: 
            srvc_mariadb:
                condition: service_healthy
        networks:
            - back
            - reverse-proxy
        env_file:
            - ./.env
        volumes:
            - .:/var/www/html
        restart: unless-stopped

    srvc_nginx:
        container_name: ${PROJECT_NAME}_nginx
        image: nginx:latest
        depends_on:
            - srvc_php
        networks:
            - back
            - reverse-proxy
        labels:
            - traefik.enable=true
            - traefik.docker.network=reverse-proxy
            - traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_NAME}.${BASE_DOMAIN}`)
            - traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=redirecthttps@file
        working_dir: /var/www/html
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
            - .:/var/www/html

    srvc_pma:
        container_name: ${PROJECT_NAME}_pma
        image: phpmyadmin
        environment:
            - PMA_HOST=${DATABASE_HOST}
            - PMA_USER=${DATABASE_USER}
            - PMA_PASSWORD=${DATABASE_PASSWORD}
        networks:
            - back
            - reverse-proxy
        labels:
            - traefik.enable=true
            - traefik.docker.network=reverse-proxy
            - traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_NAME}.${BASE_DOMAIN}`)
            - traefik.http.routers.${PROJECT_NAME}_pma.middlewares=redirecthttps@file

    srvc_mail:
        container_name: ${PROJECT_NAME}_mail
        image: djfarrelly/maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        networks:
            - back
            - reverse-proxy
        labels:
            - traefik.enable=true
            - traefik.docker.network=reverse-proxy
            - traefik.http.routers.${PROJECT_NAME}_mail.rule=Host(`mail.${PROJECT_NAME}.${BASE_DOMAIN}`)
            - traefik.http.routers.${PROJECT_NAME}_mail.middlewares=redirecthttps@file
            - traefik.http.services.${PROJECT_NAME}_mail.loadbalancer.server.port=80

volumes:
    database_data:
        name: vol-prestashop-data

